package com.jas.mappers;

import com.jas.model.TGoods;
import com.jas.model.TGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    int countByExample(TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    int deleteByExample(TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    int deleteByPrimaryKey(String merchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    int insert(TGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    int insertSelective(TGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    List<TGoods> selectByExample(TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    TGoods selectByPrimaryKey(String merchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") TGoods record, @Param("example") TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    int updateByExample(@Param("record") TGoods record, @Param("example") TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    int updateByPrimaryKeySelective(TGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    int updateByPrimaryKey(TGoods record);
    
    String selectMaxGoodsId();
}