package com.jas.mappers;

import com.jas.model.TStaffbill;
import com.jas.model.TStaffbillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TStaffbillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staffbill
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    int countByExample(TStaffbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staffbill
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    int deleteByExample(TStaffbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staffbill
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    int deleteByPrimaryKey(String staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staffbill
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    int insert(TStaffbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staffbill
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    int insertSelective(TStaffbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staffbill
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    List<TStaffbill> selectByExample(TStaffbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staffbill
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    TStaffbill selectByPrimaryKey(String staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staffbill
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") TStaffbill record, @Param("example") TStaffbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staffbill
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    int updateByExample(@Param("record") TStaffbill record, @Param("example") TStaffbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staffbill
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    int updateByPrimaryKeySelective(TStaffbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staffbill
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    int updateByPrimaryKey(TStaffbill record);
    
    String selectMaxStaffbillId();
}