package com.jas.model;

import java.util.Date;

public class TAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.login_id
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.login_password
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private String loginPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.create_by
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.create_time
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.login_id
     *
     * @return the value of t_admin.login_id
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.login_id
     *
     * @param loginId the value for t_admin.login_id
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.login_password
     *
     * @return the value of t_admin.login_password
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.login_password
     *
     * @param loginPassword the value for t_admin.login_password
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.create_by
     *
     * @return the value of t_admin.create_by
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.create_by
     *
     * @param createBy the value for t_admin.create_by
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.create_time
     *
     * @return the value of t_admin.create_time
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.create_time
     *
     * @param createTime the value for t_admin.create_time
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}