package com.jas.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TBuyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public TBuyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBuyIdIsNull() {
			addCriterion("buy_id is null");
			return (Criteria) this;
		}

		public Criteria andBuyIdIsNotNull() {
			addCriterion("buy_id is not null");
			return (Criteria) this;
		}

		public Criteria andBuyIdEqualTo(String value) {
			addCriterion("buy_id =", value, "buyId");
			return (Criteria) this;
		}

		public Criteria andBuyIdNotEqualTo(String value) {
			addCriterion("buy_id <>", value, "buyId");
			return (Criteria) this;
		}

		public Criteria andBuyIdGreaterThan(String value) {
			addCriterion("buy_id >", value, "buyId");
			return (Criteria) this;
		}

		public Criteria andBuyIdGreaterThanOrEqualTo(String value) {
			addCriterion("buy_id >=", value, "buyId");
			return (Criteria) this;
		}

		public Criteria andBuyIdLessThan(String value) {
			addCriterion("buy_id <", value, "buyId");
			return (Criteria) this;
		}

		public Criteria andBuyIdLessThanOrEqualTo(String value) {
			addCriterion("buy_id <=", value, "buyId");
			return (Criteria) this;
		}

		public Criteria andBuyIdLike(String value) {
			addCriterion("buy_id like", value, "buyId");
			return (Criteria) this;
		}

		public Criteria andBuyIdNotLike(String value) {
			addCriterion("buy_id not like", value, "buyId");
			return (Criteria) this;
		}

		public Criteria andBuyIdIn(List<String> values) {
			addCriterion("buy_id in", values, "buyId");
			return (Criteria) this;
		}

		public Criteria andBuyIdNotIn(List<String> values) {
			addCriterion("buy_id not in", values, "buyId");
			return (Criteria) this;
		}

		public Criteria andBuyIdBetween(String value1, String value2) {
			addCriterion("buy_id between", value1, value2, "buyId");
			return (Criteria) this;
		}

		public Criteria andBuyIdNotBetween(String value1, String value2) {
			addCriterion("buy_id not between", value1, value2, "buyId");
			return (Criteria) this;
		}

		public Criteria andGoodIdIsNull() {
			addCriterion("good_id is null");
			return (Criteria) this;
		}

		public Criteria andGoodIdIsNotNull() {
			addCriterion("good_id is not null");
			return (Criteria) this;
		}

		public Criteria andGoodIdEqualTo(String value) {
			addCriterion("good_id =", value, "goodId");
			return (Criteria) this;
		}

		public Criteria andGoodIdNotEqualTo(String value) {
			addCriterion("good_id <>", value, "goodId");
			return (Criteria) this;
		}

		public Criteria andGoodIdGreaterThan(String value) {
			addCriterion("good_id >", value, "goodId");
			return (Criteria) this;
		}

		public Criteria andGoodIdGreaterThanOrEqualTo(String value) {
			addCriterion("good_id >=", value, "goodId");
			return (Criteria) this;
		}

		public Criteria andGoodIdLessThan(String value) {
			addCriterion("good_id <", value, "goodId");
			return (Criteria) this;
		}

		public Criteria andGoodIdLessThanOrEqualTo(String value) {
			addCriterion("good_id <=", value, "goodId");
			return (Criteria) this;
		}

		public Criteria andGoodIdLike(String value) {
			addCriterion("good_id like", value, "goodId");
			return (Criteria) this;
		}

		public Criteria andGoodIdNotLike(String value) {
			addCriterion("good_id not like", value, "goodId");
			return (Criteria) this;
		}

		public Criteria andGoodIdIn(List<String> values) {
			addCriterion("good_id in", values, "goodId");
			return (Criteria) this;
		}

		public Criteria andGoodIdNotIn(List<String> values) {
			addCriterion("good_id not in", values, "goodId");
			return (Criteria) this;
		}

		public Criteria andGoodIdBetween(String value1, String value2) {
			addCriterion("good_id between", value1, value2, "goodId");
			return (Criteria) this;
		}

		public Criteria andGoodIdNotBetween(String value1, String value2) {
			addCriterion("good_id not between", value1, value2, "goodId");
			return (Criteria) this;
		}

		public Criteria andSuppIdIsNull() {
			addCriterion("supp_id is null");
			return (Criteria) this;
		}

		public Criteria andSuppIdIsNotNull() {
			addCriterion("supp_id is not null");
			return (Criteria) this;
		}

		public Criteria andSuppIdEqualTo(String value) {
			addCriterion("supp_id =", value, "suppId");
			return (Criteria) this;
		}

		public Criteria andSuppIdNotEqualTo(String value) {
			addCriterion("supp_id <>", value, "suppId");
			return (Criteria) this;
		}

		public Criteria andSuppIdGreaterThan(String value) {
			addCriterion("supp_id >", value, "suppId");
			return (Criteria) this;
		}

		public Criteria andSuppIdGreaterThanOrEqualTo(String value) {
			addCriterion("supp_id >=", value, "suppId");
			return (Criteria) this;
		}

		public Criteria andSuppIdLessThan(String value) {
			addCriterion("supp_id <", value, "suppId");
			return (Criteria) this;
		}

		public Criteria andSuppIdLessThanOrEqualTo(String value) {
			addCriterion("supp_id <=", value, "suppId");
			return (Criteria) this;
		}

		public Criteria andSuppIdLike(String value) {
			addCriterion("supp_id like", value, "suppId");
			return (Criteria) this;
		}

		public Criteria andSuppIdNotLike(String value) {
			addCriterion("supp_id not like", value, "suppId");
			return (Criteria) this;
		}

		public Criteria andSuppIdIn(List<String> values) {
			addCriterion("supp_id in", values, "suppId");
			return (Criteria) this;
		}

		public Criteria andSuppIdNotIn(List<String> values) {
			addCriterion("supp_id not in", values, "suppId");
			return (Criteria) this;
		}

		public Criteria andSuppIdBetween(String value1, String value2) {
			addCriterion("supp_id between", value1, value2, "suppId");
			return (Criteria) this;
		}

		public Criteria andSuppIdNotBetween(String value1, String value2) {
			addCriterion("supp_id not between", value1, value2, "suppId");
			return (Criteria) this;
		}

		public Criteria andSumIsNull() {
			addCriterion("sum is null");
			return (Criteria) this;
		}

		public Criteria andSumIsNotNull() {
			addCriterion("sum is not null");
			return (Criteria) this;
		}

		public Criteria andSumEqualTo(Integer value) {
			addCriterion("sum =", value, "sum");
			return (Criteria) this;
		}

		public Criteria andSumNotEqualTo(Integer value) {
			addCriterion("sum <>", value, "sum");
			return (Criteria) this;
		}

		public Criteria andSumGreaterThan(Integer value) {
			addCriterion("sum >", value, "sum");
			return (Criteria) this;
		}

		public Criteria andSumGreaterThanOrEqualTo(Integer value) {
			addCriterion("sum >=", value, "sum");
			return (Criteria) this;
		}

		public Criteria andSumLessThan(Integer value) {
			addCriterion("sum <", value, "sum");
			return (Criteria) this;
		}

		public Criteria andSumLessThanOrEqualTo(Integer value) {
			addCriterion("sum <=", value, "sum");
			return (Criteria) this;
		}

		public Criteria andSumIn(List<Integer> values) {
			addCriterion("sum in", values, "sum");
			return (Criteria) this;
		}

		public Criteria andSumNotIn(List<Integer> values) {
			addCriterion("sum not in", values, "sum");
			return (Criteria) this;
		}

		public Criteria andSumBetween(Integer value1, Integer value2) {
			addCriterion("sum between", value1, value2, "sum");
			return (Criteria) this;
		}

		public Criteria andSumNotBetween(Integer value1, Integer value2) {
			addCriterion("sum not between", value1, value2, "sum");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(BigDecimal value) {
			addCriterion("amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(BigDecimal value) {
			addCriterion("amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(BigDecimal value) {
			addCriterion("amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(BigDecimal value) {
			addCriterion("amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<BigDecimal> values) {
			addCriterion("amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<BigDecimal> values) {
			addCriterion("amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountIsNull() {
			addCriterion("total_amount is null");
			return (Criteria) this;
		}

		public Criteria andTotalAmountIsNotNull() {
			addCriterion("total_amount is not null");
			return (Criteria) this;
		}

		public Criteria andTotalAmountEqualTo(BigDecimal value) {
			addCriterion("total_amount =", value, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountNotEqualTo(BigDecimal value) {
			addCriterion("total_amount <>", value, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountGreaterThan(BigDecimal value) {
			addCriterion("total_amount >", value, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("total_amount >=", value, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountLessThan(BigDecimal value) {
			addCriterion("total_amount <", value, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("total_amount <=", value, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountIn(List<BigDecimal> values) {
			addCriterion("total_amount in", values, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountNotIn(List<BigDecimal> values) {
			addCriterion("total_amount not in", values, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("total_amount between", value1, value2, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("total_amount not between", value1, value2, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andBuyTimeIsNull() {
			addCriterion("buy_time is null");
			return (Criteria) this;
		}

		public Criteria andBuyTimeIsNotNull() {
			addCriterion("buy_time is not null");
			return (Criteria) this;
		}

		public Criteria andBuyTimeEqualTo(Date value) {
			addCriterion("buy_time =", value, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeNotEqualTo(Date value) {
			addCriterion("buy_time <>", value, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeGreaterThan(Date value) {
			addCriterion("buy_time >", value, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("buy_time >=", value, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeLessThan(Date value) {
			addCriterion("buy_time <", value, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeLessThanOrEqualTo(Date value) {
			addCriterion("buy_time <=", value, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeIn(List<Date> values) {
			addCriterion("buy_time in", values, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeNotIn(List<Date> values) {
			addCriterion("buy_time not in", values, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeBetween(Date value1, Date value2) {
			addCriterion("buy_time between", value1, value2, "buyTime");
			return (Criteria) this;
		}

		public Criteria andBuyTimeNotBetween(Date value1, Date value2) {
			addCriterion("buy_time not between", value1, value2, "buyTime");
			return (Criteria) this;
		}

		public Criteria andOthersIsNull() {
			addCriterion("others is null");
			return (Criteria) this;
		}

		public Criteria andOthersIsNotNull() {
			addCriterion("others is not null");
			return (Criteria) this;
		}

		public Criteria andOthersEqualTo(String value) {
			addCriterion("others =", value, "others");
			return (Criteria) this;
		}

		public Criteria andOthersNotEqualTo(String value) {
			addCriterion("others <>", value, "others");
			return (Criteria) this;
		}

		public Criteria andOthersGreaterThan(String value) {
			addCriterion("others >", value, "others");
			return (Criteria) this;
		}

		public Criteria andOthersGreaterThanOrEqualTo(String value) {
			addCriterion("others >=", value, "others");
			return (Criteria) this;
		}

		public Criteria andOthersLessThan(String value) {
			addCriterion("others <", value, "others");
			return (Criteria) this;
		}

		public Criteria andOthersLessThanOrEqualTo(String value) {
			addCriterion("others <=", value, "others");
			return (Criteria) this;
		}

		public Criteria andOthersLike(String value) {
			addCriterion("others like", value, "others");
			return (Criteria) this;
		}

		public Criteria andOthersNotLike(String value) {
			addCriterion("others not like", value, "others");
			return (Criteria) this;
		}

		public Criteria andOthersIn(List<String> values) {
			addCriterion("others in", values, "others");
			return (Criteria) this;
		}

		public Criteria andOthersNotIn(List<String> values) {
			addCriterion("others not in", values, "others");
			return (Criteria) this;
		}

		public Criteria andOthersBetween(String value1, String value2) {
			addCriterion("others between", value1, value2, "others");
			return (Criteria) this;
		}

		public Criteria andOthersNotBetween(String value1, String value2) {
			addCriterion("others not between", value1, value2, "others");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNull() {
			addCriterion("create_by is null");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNotNull() {
			addCriterion("create_by is not null");
			return (Criteria) this;
		}

		public Criteria andCreateByEqualTo(String value) {
			addCriterion("create_by =", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotEqualTo(String value) {
			addCriterion("create_by <>", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThan(String value) {
			addCriterion("create_by >", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThanOrEqualTo(String value) {
			addCriterion("create_by >=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThan(String value) {
			addCriterion("create_by <", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThanOrEqualTo(String value) {
			addCriterion("create_by <=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLike(String value) {
			addCriterion("create_by like", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotLike(String value) {
			addCriterion("create_by not like", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByIn(List<String> values) {
			addCriterion("create_by in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotIn(List<String> values) {
			addCriterion("create_by not in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByBetween(String value1, String value2) {
			addCriterion("create_by between", value1, value2, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotBetween(String value1, String value2) {
			addCriterion("create_by not between", value1, value2, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_buy
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_buy
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 11 18:54:20 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}