package com.jas.model;

import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.DateDeserializers.DateDeserializer;
import com.ins.core.pub.json.serialize.DateSerializer;

public class TBuy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_buy.buy_id
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	private String buyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_buy.good_id
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	private String goodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_buy.supp_id
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	private String suppId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_buy.sum
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	private Integer sum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_buy.amount
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	private BigDecimal amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_buy.total_amount
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	private BigDecimal totalAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_buy.buy_time
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	@JsonSerialize(using = DateSerializer.class)
	@JsonDeserialize(using = DateDeserializer.class)
	private Date buyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_buy.others
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	private String others;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_buy.create_by
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_buy.create_time
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_buy.buy_id
	 * @return  the value of t_buy.buy_id
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public String getBuyId() {
		return buyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_buy.buy_id
	 * @param buyId  the value for t_buy.buy_id
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void setBuyId(String buyId) {
		this.buyId = buyId == null ? null : buyId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_buy.good_id
	 * @return  the value of t_buy.good_id
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public String getGoodId() {
		return goodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_buy.good_id
	 * @param goodId  the value for t_buy.good_id
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void setGoodId(String goodId) {
		this.goodId = goodId == null ? null : goodId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_buy.supp_id
	 * @return  the value of t_buy.supp_id
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public String getSuppId() {
		return suppId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_buy.supp_id
	 * @param suppId  the value for t_buy.supp_id
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void setSuppId(String suppId) {
		this.suppId = suppId == null ? null : suppId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_buy.sum
	 * @return  the value of t_buy.sum
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public Integer getSum() {
		return sum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_buy.sum
	 * @param sum  the value for t_buy.sum
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void setSum(Integer sum) {
		this.sum = sum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_buy.amount
	 * @return  the value of t_buy.amount
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_buy.amount
	 * @param amount  the value for t_buy.amount
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_buy.total_amount
	 * @return  the value of t_buy.total_amount
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public BigDecimal getTotalAmount() {
		return totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_buy.total_amount
	 * @param totalAmount  the value for t_buy.total_amount
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_buy.buy_time
	 * @return  the value of t_buy.buy_time
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public Date getBuyTime() {
		return buyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_buy.buy_time
	 * @param buyTime  the value for t_buy.buy_time
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void setBuyTime(Date buyTime) {
		this.buyTime = buyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_buy.others
	 * @return  the value of t_buy.others
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public String getOthers() {
		return others;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_buy.others
	 * @param others  the value for t_buy.others
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void setOthers(String others) {
		this.others = others == null ? null : others.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_buy.create_by
	 * @return  the value of t_buy.create_by
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_buy.create_by
	 * @param createBy  the value for t_buy.create_by
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_buy.create_time
	 * @return  the value of t_buy.create_time
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_buy.create_time
	 * @param createTime  the value for t_buy.create_time
	 * @mbggenerated  Fri Nov 18 11:24:56 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}