package com.jas.model;

import java.math.BigDecimal;
import java.util.Date;

public class TGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.merch_id
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private String merchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.supp_id
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private String suppId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.merch_name
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private String merchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.kind
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private String kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.unit_cost
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private BigDecimal unitCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.merch_addr
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private String merchAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.others
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private String others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.create_by
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.create_time
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.merch_id
     *
     * @return the value of t_goods.merch_id
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public String getMerchId() {
        return merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.merch_id
     *
     * @param merchId the value for t_goods.merch_id
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setMerchId(String merchId) {
        this.merchId = merchId == null ? null : merchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.supp_id
     *
     * @return the value of t_goods.supp_id
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public String getSuppId() {
        return suppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.supp_id
     *
     * @param suppId the value for t_goods.supp_id
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setSuppId(String suppId) {
        this.suppId = suppId == null ? null : suppId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.merch_name
     *
     * @return the value of t_goods.merch_name
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public String getMerchName() {
        return merchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.merch_name
     *
     * @param merchName the value for t_goods.merch_name
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setMerchName(String merchName) {
        this.merchName = merchName == null ? null : merchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.kind
     *
     * @return the value of t_goods.kind
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.kind
     *
     * @param kind the value for t_goods.kind
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.unit_cost
     *
     * @return the value of t_goods.unit_cost
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public BigDecimal getUnitCost() {
        return unitCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.unit_cost
     *
     * @param unitCost the value for t_goods.unit_cost
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setUnitCost(BigDecimal unitCost) {
        this.unitCost = unitCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.merch_addr
     *
     * @return the value of t_goods.merch_addr
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public String getMerchAddr() {
        return merchAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.merch_addr
     *
     * @param merchAddr the value for t_goods.merch_addr
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setMerchAddr(String merchAddr) {
        this.merchAddr = merchAddr == null ? null : merchAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.others
     *
     * @return the value of t_goods.others
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.others
     *
     * @param others the value for t_goods.others
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.create_by
     *
     * @return the value of t_goods.create_by
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.create_by
     *
     * @param createBy the value for t_goods.create_by
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.create_time
     *
     * @return the value of t_goods.create_time
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.create_time
     *
     * @param createTime the value for t_goods.create_time
     *
     * @mbggenerated Fri Nov 11 18:54:20 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}