package com.jas.model;

import java.util.Date;

public class TStaffbill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staffbill.staff_id
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staffbill.stall_name
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String stallName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staffbill.stall_password
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String stallPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staffbill.sex
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staffbill.idcard
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staffbill.others
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staffbill.create_by
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staffbill.create_time
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staffbill.staff_id
     *
     * @return the value of t_staffbill.staff_id
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staffbill.staff_id
     *
     * @param staffId the value for t_staffbill.staff_id
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staffbill.stall_name
     *
     * @return the value of t_staffbill.stall_name
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getStallName() {
        return stallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staffbill.stall_name
     *
     * @param stallName the value for t_staffbill.stall_name
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setStallName(String stallName) {
        this.stallName = stallName == null ? null : stallName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staffbill.stall_password
     *
     * @return the value of t_staffbill.stall_password
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getStallPassword() {
        return stallPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staffbill.stall_password
     *
     * @param stallPassword the value for t_staffbill.stall_password
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setStallPassword(String stallPassword) {
        this.stallPassword = stallPassword == null ? null : stallPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staffbill.sex
     *
     * @return the value of t_staffbill.sex
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staffbill.sex
     *
     * @param sex the value for t_staffbill.sex
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staffbill.idcard
     *
     * @return the value of t_staffbill.idcard
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staffbill.idcard
     *
     * @param idcard the value for t_staffbill.idcard
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staffbill.others
     *
     * @return the value of t_staffbill.others
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staffbill.others
     *
     * @param others the value for t_staffbill.others
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staffbill.create_by
     *
     * @return the value of t_staffbill.create_by
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staffbill.create_by
     *
     * @param createBy the value for t_staffbill.create_by
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staffbill.create_time
     *
     * @return the value of t_staffbill.create_time
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staffbill.create_time
     *
     * @param createTime the value for t_staffbill.create_time
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}