package com.jas.model;

import java.util.Date;

public class TSupplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.supp_id
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String suppId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.supp_name
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String suppName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.contact_person
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String contactPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.telphone
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.address
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.others
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.create_by
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.create_time
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.supp_id
     *
     * @return the value of t_supplier.supp_id
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getSuppId() {
        return suppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.supp_id
     *
     * @param suppId the value for t_supplier.supp_id
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setSuppId(String suppId) {
        this.suppId = suppId == null ? null : suppId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.supp_name
     *
     * @return the value of t_supplier.supp_name
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getSuppName() {
        return suppName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.supp_name
     *
     * @param suppName the value for t_supplier.supp_name
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setSuppName(String suppName) {
        this.suppName = suppName == null ? null : suppName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.contact_person
     *
     * @return the value of t_supplier.contact_person
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.contact_person
     *
     * @param contactPerson the value for t_supplier.contact_person
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.telphone
     *
     * @return the value of t_supplier.telphone
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.telphone
     *
     * @param telphone the value for t_supplier.telphone
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.address
     *
     * @return the value of t_supplier.address
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.address
     *
     * @param address the value for t_supplier.address
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.others
     *
     * @return the value of t_supplier.others
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.others
     *
     * @param others the value for t_supplier.others
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.create_by
     *
     * @return the value of t_supplier.create_by
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.create_by
     *
     * @param createBy the value for t_supplier.create_by
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.create_time
     *
     * @return the value of t_supplier.create_time
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.create_time
     *
     * @param createTime the value for t_supplier.create_time
     *
     * @mbggenerated Fri Nov 11 18:54:21 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}